[package]
name = "ellalgo-rs"
version = "0.1.1"
edition = "2021"
description = "Ellipsoid Method in Rust"
repository = "https://github.com/luk036/ellalgo-rs"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.4"
# ndarray-linalg = "0.16.0"
svgbobdoc = { version = "0.3", features = ["enable"] }

[dev-dependencies]
approx_eq = "0.1.8"
